name: GH Deployment 2020-02-17

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 12.x # optional, default is 10.x
    - uses: actions/checkout@v2
    - name: NPM install
      run: npm install
    - name: Install Gridsome
      run: npm install --global @gridsome/cli 
    - name: Process
      run: gridsome build
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env: 
        BUILD_DIR : "dist/"

