name: Deploy Master to Azure Blob Storage

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 12.x # optional, default is 10.x
    - uses: actions/checkout@v2
    - name: NPM install
      run: npm install
    - name: NPM link local plugins
      run: npm link ./localPlugins/email-cta-insert
    - name: Install Gridsome
      run: npm install --global @gridsome/cli 
    - name: Gridsome Build
      run: gridsome build
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        # The name of the directory you want to upload
        source_dir: dist
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string: ${{secrets.AZURE_BLOB_CONNECTIONSTRING}}
    

