# This is a basic workflow to help you get started with Actions

name: Schedule Future Posts

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: "*/30 * * * *"
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          #  Time zone to use. Default is UTC.
          time_zone: "America/New_York"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
